# TinyUSB MSC command-boundary hook; SDK source is never modified.
set(msc_source "${PICO_SDK_PATH}/lib/tinyusb/src/class/msc/msc_device.c")
file(SHA256 "${msc_source}" msc_hash)
if(NOT msc_hash STREQUAL "4604d18946f41a71e1b1be898a0fe1179d2b0b5973a1240fb4a61fe3f23f0c17")
  message(FATAL_ERROR "TinyUSB MSC source changed: review the command-boundary patch before updating its hash")
endif()
file(READ "${msc_source}" msc_code)
string(REPLACE "#include \"msc_device.h\"" "#include \"class/msc/msc_device.h\"\n#include \"usb_storage.h\"" msc_code "${msc_code}")
string(REPLACE "} else if (p_cbw->total_bytes) {" "} else if (p_cbw->total_bytes && !fv_usb_storage_begin(p_cbw->lun, SCSI_CMD_WRITE_10 == p_cbw->command[0], rdwr10_get_lba(p_cbw->command), p_cbw->total_bytes, rdwr10_get_blocksize(p_cbw))) {\n          fail_scsi_op(rhport, p_msc, MSC_CSW_STATUS_FAILED);\n        } else if (p_cbw->total_bytes) {" msc_code "${msc_code}")
string(REPLACE "proc_bot_reset(p_msc); // driver state reset" "fv_usb_storage_clear_transport(); // drain worker before discarding command buffers\n      proc_bot_reset(p_msc); // driver state reset" msc_code "${msc_code}")
file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/msc_device_pipeline.c" "${msc_code}")
get_target_property(tinyusb_sources tinyusb_device_base INTERFACE_SOURCES)
list(FILTER tinyusb_sources EXCLUDE REGEX "/class/msc/msc_device\\.c$")
set_property(TARGET tinyusb_device_base PROPERTY INTERFACE_SOURCES "${tinyusb_sources}")
target_sources(fuse_vault_security PRIVATE "${CMAKE_CURRENT_BINARY_DIR}/msc_device_pipeline.c")
