#ifndef FV_BENCH_TUSB_CONFIG_H
#define FV_BENCH_TUSB_CONFIG_H
#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_NONE
#endif
#define CFG_TUD_ENABLED 1
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 1
#define CFG_TUD_CDC_RX_BUFSIZE 4096
#define CFG_TUD_CDC_TX_BUFSIZE 4096
#define CFG_TUD_CDC_EP_BUFSIZE 64
#if FV_USB_MSC
#define CFG_TUD_MSC 1
#include "usb_storage.h"
#define CFG_TUD_MSC_EP_BUFSIZE FV_USB_IO_BYTES
#else
#define CFG_TUD_MSC 0
#endif
#define CFG_TUD_HID 0
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#endif
