#!/usr/bin/env python3
"""Independent fixtures, Python hashlib/hmac + cryptography/OpenSSL ciphers.
Run explicitly to regenerate tests/fixtures/envelope_vectors.h. No production use.
Seeded byte stream and cost=3 are ONLY for reproducible tests.
"""
import hashlib
import hmac
from pathlib import Path
from struct import pack
from cryptography.hazmat.primitives.ciphers import Cipher, algorithms, modes
from cryptography.hazmat.primitives.keywrap import aes_key_wrap

def mac(k, b): return hmac.digest(k, b, 'sha256')
def label(s): return s.encode() + b'\0'
def expand(prk, info): return mac(prk, info + b'\1')
def camellia_wrap(key, data):
    a = b'\xa6' * 8
    r = [data[i:i+8] for i in range(0, len(data), 8)]
    cipher = Cipher(algorithms.Camellia(key), modes.ECB()).encryptor()
    for j in range(6):
        for i in range(len(r)):
            b = cipher.update(a + r[i])
            a = (int.from_bytes(b[:8], 'big') ^ (len(r)*j+i+1)).to_bytes(8, 'big')
            r[i] = b[8:]
    assert cipher.finalize() == b''
    return a + b''.join(r)

def fixture(ids):
    h = bytearray(512)
    def put(off, data): h[off:off+len(data)] = data
    put(0, b'FV2VOL01');put(8, pack('<HHI', 1, 512, 0));put(16, bytes(range(1,17)))
    put(32, pack('<IHH',512,1,1));put(40, pack('<QQQQQQ',64,2064,5,2069,16,2048))
    put(88,bytes([len(ids),1]));put(92,b''.join(pack('<H',i) for i in ids))
    put(128,bytes(range(17,33)));put(144,pack('<QHHI',7,1,1,3))
    put(160,bytes(range(32)));put(192,pack('<HBBHHII',0x101,len(ids),0,40*len(ids),0,9,0))
    put(208,pack('<HHIH',1,16,10,1));put(224,b''.join(pack('<H',i) for i in ids))
    root,token,vmk=bytes(range(32)),bytes(range(32,64)),bytes(range(64,96))
    binding=mac(root,label('FV2/vault-binding/v1')+pack('<I',9)+h[16:32]+token)
    ctx=hashlib.sha256(h[:128]).digest()+h[128:256]
    secret=b'a\0test password'
    bound=mac(binding,label('FV2/unlock-input/v2')+ctx+pack('<I',len(secret))+secret)
    password=hashlib.pbkdf2_hmac('sha256',bound,label('FV2/password-salt/v1')+h[160:192],3,32)
    prk=mac(h[160:192],password)
    remainder=int.from_bytes(vmk,'big')
    wraps=[]
    for i, algorithm in enumerate(ids):
        if i<len(ids)-1:
            share=bytes(range(32*(i+1),32*(i+2)))
            remainder ^= int.from_bytes(share,'big')
        else: share=remainder.to_bytes(32,'big')
        key=expand(prk,label('FV2/share-wrap/v1')+ctx+pack('<IH',i,algorithm))
        wrapped=(aes_key_wrap if algorithm==1 else camellia_wrap)(key,share)
        put(256+40*i,wrapped)
        wraps.append((key,share,wrapped))
    mac_key=expand(prk,label('FV2/envelope-mac/v1')+ctx)
    def tag():put(416,mac(mac_key,label('FV2/envelope/v1')+h[:416]+h[448:]))
    tag()
    good=bytes(h)
    # Correct outer tag but corrupted last KW: must not publish partial VMK.
    h[256+40*(len(ids)-1)+8]^=1;tag()
    return binding,good,bytes(h),wraps

def array(name,data):
    rows=['    '+','.join(f'0x{b:02x}' for b in data[i:i+16])+',' for i in range(0,len(data),16)]
    return f'static const uint8_t {name}[{len(data)}] = {{\n'+ '\n'.join(rows)+'\n};\n'

out='/* Generated by tests/envelope_reference.py; test secrets ONLY. */\n'
for name,ids in [('aes',[1]),('cam',[2]),('pair',[1,2]),('three',[1,2,1]),('four',[2,1,2,1])]:
    binding,good,bad,wraps=fixture(ids)
    out+=array(name+'_binding',binding)+array(name+'_header',good)+array(name+'_bad_kw',bad)
    for i,(key,share,wrapped) in enumerate(wraps):
        out+=array(f'{name}_key_{i}',key)+array(f'{name}_share_{i}',share)+array(f'{name}_wrapped_{i}',wrapped)
Path(__file__).with_name('fixtures').joinpath('envelope_vectors.h').write_text(out)
