#include "fuse_vault/security.h"
#include <openssl/evp.h>
#include <openssl/kdf.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#define CHECK(x) do {if(!(x)){fprintf(stderr,"%s:%d: %s\n",__FILE__,__LINE__,#x);exit(1);}}while(0)
static bool zero(const void *v,size_t n){const unsigned char*p=v;while(n--)if(*p++)return false;return true;}
static void reference_hkdf(const uint8_t *salt,int sn,const uint8_t *ikm,int kn,const uint8_t *info,int in,uint8_t *out,size_t n){
 EVP_PKEY_CTX *c=EVP_PKEY_CTX_new_id(EVP_PKEY_HKDF,NULL);CHECK(c);
 CHECK(EVP_PKEY_derive_init(c)>0);CHECK(EVP_PKEY_CTX_set_hkdf_md(c,EVP_sha256())>0);
 CHECK(EVP_PKEY_CTX_set1_hkdf_salt(c,salt,sn)>0);CHECK(EVP_PKEY_CTX_set1_hkdf_key(c,ikm,kn)>0);
 CHECK(EVP_PKEY_CTX_add1_hkdf_info(c,info,in)>0);CHECK(EVP_PKEY_derive(c,out,&n)>0);EVP_PKEY_CTX_free(c);
}
int main(void){
 fv_volume_descriptor d={.volume_id={1},.logical_blocks=2048,.layer_count=2,.cipher_ids={1,2}},decoded;
 uint8_t header[128],bad[128],out[128],prk[32],expected[128];
 CHECK(fv_volume_descriptor_encode(&d,4249,header));CHECK(fv_volume_descriptor_decode(header,128,4249,&decoded));
 CHECK(decoded.logical_blocks==2048 && decoded.layer_count==2 && decoded.cipher_ids[1]==2);
 CHECK(!fv_volume_descriptor_encode(&d,4248,out));CHECK(zero(out,128));
 CHECK(!fv_volume_descriptor_decode(header,127,4249,&decoded));CHECK(zero(&decoded,sizeof(decoded)));
 const unsigned fixed[]={0,8,10,12,32,36,38,48,56,64,72,80,89,90,96,100,127};
 for(unsigned i=0;i<sizeof(fixed)/sizeof(*fixed);i++){memcpy(bad,header,128);bad[fixed[i]]^=1;CHECK(!fv_volume_descriptor_decode(bad,128,UINT64_MAX,&decoded));CHECK(zero(&decoded,sizeof(decoded)));}
 d.logical_blocks=UINT64_MAX;CHECK(!fv_volume_descriptor_encode(&d,UINT64_MAX,out));
 d.logical_blocks=2048;d.layer_count=0;CHECK(!fv_volume_descriptor_encode(&d,UINT64_MAX,out));d.layer_count=2;
 d.cipher_ids[1]=99;CHECK(!fv_volume_descriptor_encode(&d,UINT64_MAX,out));d.cipher_ids[1]=2;
 fv_auth_policy policy=fv_auth_policy_default(),p;
 CHECK(policy.max_attempts==10 && policy.limit_action==FV_LIMIT_DESTROY);
 CHECK(fv_auth_policy_encode(&policy,out));CHECK(fv_auth_policy_decode(out,16,&p));CHECK(p.max_attempts==10 && p.limit_action==FV_LIMIT_DESTROY);
 out[15]=1;CHECK(!fv_auth_policy_decode(out,16,&p));CHECK(zero(&p,sizeof(p)));
 policy.max_attempts=0;CHECK(!fv_auth_policy_encode(&policy,out));CHECK(zero(out,16));
 policy.max_attempts=7;policy.limit_action=FV_LIMIT_LOCKOUT;CHECK(fv_auth_policy_encode(&policy,out));
 policy.limit_action=FV_LIMIT_DELAY_RESERVED;CHECK(!fv_auth_policy_encode(&policy,out));
 /* RFC 5869 test case 1: standard output, not generated by our implementation. */
 uint8_t ikm[22],salt[13],info[10];memset(ikm,0x0b,sizeof(ikm));for(unsigned i=0;i<13;i++)salt[i]=(uint8_t)i;for(unsigned i=0;i<10;i++)info[i]=(uint8_t)(0xf0+i);
 const uint8_t okm[42]={0x3c,0xb2,0x5f,0x25,0xfa,0xac,0xd5,0x7a,0x90,0x43,0x4f,0x64,0xd0,0x36,0x2f,0x2a,0x2d,0x2d,0x0a,0x90,0xcf,0x1a,0x5a,0x4c,0x5d,0xb0,0x2d,0x56,0xec,0xc4,0xc5,0xbf,0x34,0x00,0x72,0x08,0xd5,0xb8,0x87,0x18,0x58,0x65};
 CHECK(!fv_hkdf_extract(salt,13,ikm,22,prk));CHECK(!fv_hkdf_expand(prk,info,10,out,42));CHECK(!memcmp(out,okm,42));
 CHECK(!fv_hkdf_extract(NULL,0,ikm,22,prk));CHECK(!fv_hkdf_expand(prk,NULL,0,out,64));
 reference_hkdf((const uint8_t*)"",0,ikm,22,(const uint8_t*)"",0,expected,64);CHECK(!memcmp(out,expected,64));
 uint8_t maxout[8160],maxref[8160],longinfo[256];memset(longinfo,0x3c,sizeof(longinfo));
 CHECK(!fv_hkdf_extract(salt,13,ikm,22,prk));CHECK(!fv_hkdf_expand(prk,longinfo,256,maxout,sizeof(maxout)));
 reference_hkdf(salt,13,ikm,22,longinfo,256,maxref,sizeof(maxref));CHECK(!memcmp(maxout,maxref,sizeof(maxout)));
 CHECK(fv_hkdf_expand(prk,info,10,out,8161));
 CHECK(fv_hkdf_expand(prk,info,257,out,32));CHECK(zero(out,32));
 CHECK(fv_hkdf_extract(NULL,1,ikm,22,prk));CHECK(zero(prk,32));
 const uint8_t password[]={0,1,2,0,255};
 for(unsigned i=0;i<3;i++){unsigned rounds=(unsigned[]){1,2,4096}[i];CHECK(!fv_pbkdf2_sha256_32(password,sizeof(password),salt,13,rounds,out));CHECK(PKCS5_PBKDF2_HMAC((const char*)password,sizeof(password),salt,13,rounds,EVP_sha256(),32,expected));CHECK(!memcmp(out,expected,32));}
 CHECK(!fv_pbkdf2_sha256_32(NULL,0,NULL,0,1,out));CHECK(PKCS5_PBKDF2_HMAC("",0,(const uint8_t*)"",0,1,EVP_sha256(),32,expected));CHECK(!memcmp(out,expected,32));
 CHECK(fv_pbkdf2_sha256_32(password,sizeof(password),salt,13,0,out));CHECK(zero(out,32));
 uint8_t vmk[32]={7},digest[32],ctx[96];fv_working_keys keys,changed;
 CHECK(!fv_derive_working_keys(vmk,&d,&keys));unsigned hash_bytes=0;CHECK(EVP_Digest(header,128,digest,&hash_bytes,EVP_sha256(),NULL));CHECK(hash_bytes==32);
 const char label[]="FV2/xts-layer/v1";size_t n=sizeof(label);memcpy(ctx,label,n);memcpy(ctx+n,digest,32);n+=32;memset(ctx+n,0,6);ctx[n+4]=1;n+=6;
 reference_hkdf(d.volume_id,16,vmk,32,ctx,(int)n,expected,64);CHECK(!memcmp(keys.layers[0],expected,64));
 const char maclabel[]="FV2/sector-hmac/v1";memcpy(ctx,maclabel,sizeof(maclabel));memcpy(ctx+sizeof(maclabel),digest,32);
 reference_hkdf(d.volume_id,16,vmk,32,ctx,sizeof(maclabel)+32,expected,32);CHECK(!memcmp(keys.integrity,expected,32));
 CHECK(memcmp(keys.layers[0],keys.layers[1],64));CHECK(memcmp(keys.layers[0],keys.integrity,32));CHECK(zero(keys.layers[2],128));
 d.cipher_ids[1]=1;CHECK(!fv_derive_working_keys(vmk,&d,&changed));CHECK(memcmp(changed.layers[0],changed.layers[1],64));
 d.volume_id[0]=2;CHECK(!fv_derive_working_keys(vmk,&d,&changed));CHECK(memcmp(keys.integrity,changed.integrity,32));
 d.layer_count=0;CHECK(fv_derive_working_keys(vmk,&d,&changed));CHECK(zero(&changed,sizeof(changed)));
 fv_working_keys_clear(&keys);CHECK(zero(&keys,sizeof(keys)));
 puts("volume descriptor, policy and key derivation checks passed");return 0;
}
