add_executable(fido_usb_scheduling_tests tests/usb_storage_bridge_tests.c ${FV_PICO}/device/usb_storage_bridge.c)
target_include_directories(fido_usb_scheduling_tests PRIVATE ${FV_SHARED}/fido/include tests/msc_stubs ${FV_PICO}/device ${FV_SHARED}/ui)
target_compile_definitions(fido_usb_scheduling_tests PRIVATE FV_USB_FIDO=1 FV_USB_MSC=1 FV_DEVICE_UI=1)
target_link_libraries(fido_usb_scheduling_tests PRIVATE fv_security)
add_test(NAME fido_usb_scheduling COMMAND fido_usb_scheduling_tests)
add_executable(fido_transport_tests tests/fido_transport_tests.c)
target_link_libraries(fido_transport_tests PRIVATE fv_fido_transport)
target_compile_options(fido_transport_tests PRIVATE -UNDEBUG)
add_test(NAME fido_transport COMMAND fido_transport_tests)
add_library(fido_test_platform STATIC tests/fido_test_platform.c)
target_include_directories(fido_test_platform PUBLIC tests)
target_link_libraries(fido_test_platform PUBLIC fv_fido_store)
target_compile_options(fido_test_platform PRIVATE -UNDEBUG -Wall -Wextra -Werror)
add_executable(fido_adapter_peer tests/fido_adapter_peer.c)
target_include_directories(fido_adapter_peer PRIVATE tests/fido_stubs tests/msc_stubs ${FV_SHARED}/ui ${FV_PICO}/device ${FV_ROOT}/third_party/tinycbor)
target_compile_definitions(fido_adapter_peer PRIVATE FV_USB_MSC=1 FV_DEVICE_UI=1 FV_USB_FIDO=1)
target_compile_options(fido_adapter_peer PRIVATE -UNDEBUG)
target_link_libraries(fido_adapter_peer PRIVATE fv_fido_engine fv_fido_transport fido_test_platform OpenSSL::Crypto fv_ui)
add_test(NAME fido_firmware_adapter COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_adapter_reference_tests.py $<TARGET_FILE:fido_adapter_peer>)
set_tests_properties(fido_firmware_adapter PROPERTIES TIMEOUT 60)
add_executable(fido_store_tests tests/fido_store_tests.c)
target_compile_definitions(fido_store_tests PRIVATE FV_LEGACY_IMAGE="${CMAKE_CURRENT_SOURCE_DIR}/tests/fixtures/fido64-image.bin")
target_link_libraries(fido_store_tests PRIVATE fido_test_platform)
target_compile_options(fido_store_tests PRIVATE -UNDEBUG -Wall -Wextra -Werror)
add_test(NAME fido_store COMMAND fido_store_tests)
set(fv_fatfs "${FV_ROOT}/third_party/pico_sd/src")
add_executable(new_vault_tests tests/new_vault_tests.c ${FV_PICO}/device/vault_filesystem.c
  ${fv_fatfs}/ff15/source/ff.c ${fv_fatfs}/ff15/source/ffsystem.c ${fv_fatfs}/ff15/source/ffunicode.c)
target_include_directories(new_vault_tests PRIVATE ${FV_PICO}/device ${fv_fatfs}/ff15/source ${fv_fatfs}/include)
target_link_libraries(new_vault_tests PRIVATE fv_fido_store)
target_compile_options(new_vault_tests PRIVATE -UNDEBUG)
foreach(callback disk_initialize disk_status disk_read disk_write disk_ioctl)
  target_link_options(new_vault_tests PRIVATE -Wl,--wrap=${callback})
endforeach()
add_test(NAME new_vault_setup COMMAND new_vault_tests)
add_executable(fido_engine_tests tests/fido_engine_tests.c)
target_link_libraries(fido_engine_tests PRIVATE fv_fido_engine fv_fido_store OpenSSL::Crypto)
target_compile_options(fido_engine_tests PRIVATE -UNDEBUG)
target_link_options(fido_engine_tests PRIVATE -Wl,--gc-sections)
add_test(NAME fido_engine COMMAND fido_engine_tests)
add_test(NAME fido_image_migration COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_image_migration_tests.py $<TARGET_FILE:fido_engine_tests>)
execute_process(COMMAND ${Python3_EXECUTABLE} -c "import fido2, cryptography"
  RESULT_VARIABLE FV_FIDO_CLIENT_MISSING OUTPUT_QUIET ERROR_QUIET)
if(FV_FIDO_CLIENT_MISSING)
  message(FATAL_ERROR "FIDO tests require python-fido2 and cryptography in ${Python3_EXECUTABLE}")
endif()
add_test(NAME fido_web_http COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_web_http_tests.py)
add_test(NAME fido_web COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_web_tests.py $<TARGET_FILE:fido_encrypted_engine_tests>)
set_tests_properties(fido_web PROPERTIES TIMEOUT 120)
add_test(NAME fido_engine_reference COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_engine_reference_tests.py
  $<TARGET_FILE:fido_engine_tests>)
add_executable(fido_encrypted_engine_tests tests/fido_engine_tests.c)
target_compile_definitions(fido_encrypted_engine_tests PRIVATE FV_FIDO_ENCRYPTED_TEST=1)
target_compile_options(fido_encrypted_engine_tests PRIVATE -UNDEBUG)
target_link_libraries(fido_encrypted_engine_tests PRIVATE fv_fido_engine fido_test_platform OpenSSL::Crypto)
target_link_options(fido_encrypted_engine_tests PRIVATE -Wl,--gc-sections)
add_test(NAME fido_encrypted_engine COMMAND fido_encrypted_engine_tests)
add_test(NAME fido_encrypted_reference COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_engine_reference_tests.py
  $<TARGET_FILE:fido_encrypted_engine_tests> --encrypted)
set_tests_properties(fido_engine fido_engine_reference fido_store
  fido_encrypted_engine fido_encrypted_reference PROPERTIES TIMEOUT 120)

add_executable(fido_journal_peer tests/fido_journal_peer.c)
target_compile_options(fido_journal_peer PRIVATE -UNDEBUG)
target_link_libraries(fido_journal_peer PRIVATE fv_fido_engine fido_test_platform OpenSSL::Crypto)
add_test(NAME fido_journal_reference COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/fido_journal_reference_tests.py $<TARGET_FILE:fido_journal_peer>)
set_tests_properties(fido_journal_reference PROPERTIES TIMEOUT 900)
add_executable(fido_journal_tests tests/fido_journal_tests.c)
target_compile_options(fido_journal_tests PRIVATE -UNDEBUG -Wall -Wextra -Werror)
target_link_libraries(fido_journal_tests PRIVATE fido_test_platform)
add_test(NAME fido_journal_interruptions COMMAND fido_journal_tests)
set_tests_properties(fido_journal_interruptions PROPERTIES TIMEOUT 1800)
