# Host tests, including Pico adapters compiled against simulated hardware.
add_executable(crypto_tests tests/crypto_tests.c)
target_link_libraries(crypto_tests PRIVATE fv_crypto OpenSSL::Crypto)
add_test(NAME crypto COMMAND crypto_tests)
add_executable(crypto_bench tools/crypto_bench.c)
target_link_libraries(crypto_bench PRIVATE fv_crypto)
add_executable(sd_native_tests tests/sd_native_tests.c ${FV_PICO}/platform/sd_native.c)
target_include_directories(sd_native_tests PRIVATE tests/sd_stubs
  ${FV_PICO}/platform/include ${FV_PICO}/platform/boards ${FV_SHARED}/storage/include)
target_compile_definitions(sd_native_tests PRIVATE FUSE_VAULT_SD_CARD_DETECT_POLARITY_CONFIRMED=1
  FUSE_VAULT_SD_CARD_DETECT_ACTIVE_LEVEL=1)
target_compile_options(sd_native_tests PRIVATE -UNDEBUG)
add_test(NAME sd_native COMMAND sd_native_tests)
add_executable(benchmark_tests tests/benchmark_tests.c)
target_link_libraries(benchmark_tests PRIVATE fv_benchmark)
add_test(NAME benchmark_engine COMMAND benchmark_tests)
add_executable(benchmark_peer tests/benchmark_peer.c)
target_link_libraries(benchmark_peer PRIVATE fv_benchmark)
add_test(NAME board_bench_protocol COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/board_bench_tests.py $<TARGET_FILE:benchmark_peer>)
add_executable(auth_store_tests tests/auth_store_tests.c)
target_link_libraries(auth_store_tests PRIVATE fv_storage OpenSSL::Crypto)
add_test(NAME authenticated_storage COMMAND auth_store_tests)
function(fv_mock_pico_hmac target)
  target_sources(${target} PRIVATE ${FV_SHARED}/crypto/hmac.c ${FV_SHARED}/crypto/hmac_self_test.c
    ${FV_PICO}/crypto/pico_hmac.c tests/sha_sdk_fake.c)
  target_include_directories(${target} PRIVATE tests/sha_stubs)
  target_compile_definitions(${target} PRIVATE FV_HMAC_PICO=1)
endfunction()
add_executable(hmac_pico_tests tests/hmac_pico_tests.c)
fv_mock_pico_hmac(hmac_pico_tests)
target_link_libraries(hmac_pico_tests PRIVATE fv_crypto)
add_test(NAME pico_hmac_contract COMMAND hmac_pico_tests)
add_executable(auth_store_pico_tests tests/auth_store_tests.c)
fv_mock_pico_hmac(auth_store_pico_tests)
target_link_libraries(auth_store_pico_tests PRIVATE fv_storage OpenSSL::Crypto)
add_test(NAME pico_hmac_storage COMMAND auth_store_pico_tests)
add_executable(benchmark_peer_pico tests/benchmark_peer.c)
fv_mock_pico_hmac(benchmark_peer_pico)
target_link_libraries(benchmark_peer_pico PRIVATE fv_benchmark)
add_test(NAME pico_hmac_pipeline COMMAND ${Python3_EXECUTABLE}
  ${CMAKE_CURRENT_SOURCE_DIR}/tests/board_bench_tests.py $<TARGET_FILE:benchmark_peer_pico>)
add_executable(security_tests tests/security_tests.c)
target_link_libraries(security_tests PRIVATE fv_security OpenSSL::Crypto)
add_test(NAME volume_policy_derivation COMMAND security_tests)
add_executable(security_pico_tests tests/security_tests.c)
fv_mock_pico_hmac(security_pico_tests)
target_link_libraries(security_pico_tests PRIVATE fv_security OpenSSL::Crypto)
add_test(NAME volume_policy_derivation_pico_contract COMMAND security_pico_tests)
foreach(name envelope vault)
  add_executable(${name}_tests tests/${name}_tests.c)
  target_link_libraries(${name}_tests PRIVATE fv_security)
  target_compile_options(${name}_tests PRIVATE -Wall -Wextra -Werror)
  add_test(NAME ${name} COMMAND ${name}_tests)
  add_executable(${name}_pico_tests tests/${name}_tests.c)
  fv_mock_pico_hmac(${name}_pico_tests)
  target_link_libraries(${name}_pico_tests PRIVATE fv_security)
  target_compile_options(${name}_pico_tests PRIVATE -Wall -Wextra -Werror)
  add_test(NAME ${name}_pico_contract COMMAND ${name}_pico_tests)
endforeach()
add_executable(random_tests tests/random_tests.c)
target_link_libraries(random_tests PRIVATE fv_security)
target_compile_options(random_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME cryptographic_random COMMAND random_tests)
add_test(NAME security_probe COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/security_probe_tests.py)
add_test(NAME ram_debug COMMAND ${Python3_EXECUTABLE} ${CMAKE_CURRENT_SOURCE_DIR}/tests/ram_debug_tests.py)
add_executable(otp_inspect_tests tests/otp_inspect_tests.c ${FV_PICO}/platform/otp_inspect.c)
target_include_directories(otp_inspect_tests PRIVATE tests/otp_stubs ${FV_PICO}/platform/include)
target_compile_definitions(otp_inspect_tests PRIVATE FV_DEBUG_OTP_INSPECT=1)
target_compile_options(otp_inspect_tests PRIVATE -Wall -Wextra -Werror)
target_link_libraries(otp_inspect_tests PRIVATE fv_crypto)
add_test(NAME otp_inspection_contract COMMAND otp_inspect_tests)
add_executable(persistence_tests tests/persistence_tests.c)
target_link_libraries(persistence_tests PRIVATE fv_security)
target_compile_options(persistence_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME persistent_authority COMMAND persistence_tests)
add_executable(persistence_pico_tests tests/persistence_tests.c)
fv_mock_pico_hmac(persistence_pico_tests)
target_link_libraries(persistence_pico_tests PRIVATE fv_security)
target_compile_options(persistence_pico_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME persistent_authority_pico_contract COMMAND persistence_pico_tests)

add_executable(usb_storage_tests tests/usb_storage_tests.c ${FV_PICO}/device/usb_storage.c)
target_include_directories(usb_storage_tests PRIVATE tests/msc_stubs ${FV_PICO}/device ${FV_SHARED}/storage/include)
target_compile_options(usb_storage_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME usb_storage_callbacks COMMAND usb_storage_tests)
add_executable(usb_storage_bridge_tests tests/usb_storage_bridge_tests.c ${FV_PICO}/device/usb_storage_bridge.c)
target_include_directories(usb_storage_bridge_tests PRIVATE tests/msc_stubs ${FV_PICO}/device ${FV_SHARED}/storage/include)
target_compile_definitions(usb_storage_bridge_tests PRIVATE FV_USB_MSC=1)
target_compile_options(usb_storage_bridge_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME usb_storage_invalidation COMMAND usb_storage_bridge_tests)

add_executable(device_ui_tests tests/device_ui_tests.c)
target_include_directories(device_ui_tests PRIVATE ${FV_SHARED}/ui)
target_link_libraries(device_ui_tests PRIVATE fv_storage fv_ui)
target_compile_options(device_ui_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME device_ui_and_capacity COMMAND device_ui_tests)
add_executable(usb_storage_ui_bridge_tests tests/usb_storage_bridge_tests.c ${FV_PICO}/device/usb_storage_bridge.c)
target_include_directories(usb_storage_ui_bridge_tests PRIVATE tests/msc_stubs ${FV_PICO}/device ${FV_SHARED}/storage/include ${FV_SHARED}/ui)
target_compile_definitions(usb_storage_ui_bridge_tests PRIVATE FV_USB_MSC=1 FV_DEVICE_UI=1)
target_compile_options(usb_storage_ui_bridge_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME usb_storage_during_setup COMMAND usb_storage_ui_bridge_tests)
add_executable(format_progress_tests tests/format_progress_tests.c)
target_link_libraries(format_progress_tests PRIVATE fv_storage)
target_compile_options(format_progress_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME metadata_format_progress COMMAND format_progress_tests)
add_executable(bitmap_store_tests tests/bitmap_store_tests.c)
target_link_libraries(bitmap_store_tests PRIVATE fv_storage)
target_compile_options(bitmap_store_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME lazy_metadata_bitmap COMMAND bitmap_store_tests)

add_executable(tft_display_tests tests/tft_display_tests.c ${FV_PICO}/platform/tft_display.c)
target_include_directories(tft_display_tests PRIVATE tests/tft_stubs ${FV_PICO}/platform/include ${FV_PICO}/platform/boards)
target_compile_options(tft_display_tests PRIVATE -Wall -Wextra -Werror -UNDEBUG)
add_test(NAME tft_display_transport COMMAND tft_display_tests)

add_executable(ui_components_tests tests/ui_components_tests.c)
target_link_libraries(ui_components_tests PRIVATE fv_ui)
target_compile_options(ui_components_tests PRIVATE -Wall -Wextra -Werror)
add_test(NAME ui_components COMMAND ui_components_tests)
