#ifndef FV_MBEDTLS_CONFIG_H
#define FV_MBEDTLS_CONFIG_H
#define MBEDTLS_SHA256_C
#define MBEDTLS_CTR_DRBG_C
#define MBEDTLS_AES_C
#define MBEDTLS_CAMELLIA_C
#define MBEDTLS_CIPHER_MODE_XTS
#define MBEDTLS_SELF_TEST
#endif
