"""Verify real credentials generated by the old 64 KiB engine after expansion."""
import hashlib
import json
from pathlib import Path
import subprocess
import sys
from fido2.cose import ES256
from fido_engine_reference_tests import Device, Ctap2, ClientPin, PinProtocolV2, CredentialManagement


def main():
    fixtures = Path(__file__).with_name('fixtures')
    device = Device.__new__(Device)
    device.proc = subprocess.Popen([sys.argv[1], '--legacy', str(fixtures / 'fido64-image.bin')],
                                   stdin=subprocess.PIPE, stdout=subprocess.PIPE, text=True)
    records = json.loads((fixtures / 'fido64-credentials.json').read_text())
    try:
        for repeat in range(2):
            ctap = Ctap2(device)
            for record in records:
                challenge = hashlib.sha256(f'migration-{repeat}'.encode()).digest()
                result = ctap.get_assertion('migration.example', challenge,
                    allow_list=[{'type': 'public-key', 'id': bytes.fromhex(record['id'])}],
                    options={'uv': True})
                key = ES256({int(k): bytes.fromhex(v) if isinstance(v, str) else v
                             for k, v in record['public_key'].items()})
                key.verify(bytes(result.auth_data) + challenge, result.signature)
            pin = ClientPin(ctap, PinProtocolV2())
            token = pin.get_uv_token(ClientPin.PERMISSION.CREDENTIAL_MGMT)
            management = CredentialManagement(ctap, pin.protocol, token)
            assert management.get_metadata()[CredentialManagement.RESULT.EXISTING_CRED_COUNT] == 2 + repeat
            # Discoverable assertions must also still locate both migrated users.
            result = ctap.get_assertion('migration.example', bytes(32), options={'uv': True})
            assert result.number_of_credentials == 2
            if repeat == 0:
                ctap.make_credential(bytes(32), {'id': 'new.example'},
                    {'id': b'new', 'name': 'New account'}, [{'type':'public-key','alg':-7}],
                    options={'rk': True, 'uv': True})
                device.control('reopen')
        print('Migrated resident/nonresident signatures, discovery, new registration and reopen passed')
    finally:
        device.close()


if __name__ == '__main__':
    main()
