#!/usr/bin/env python3
"""Run the actual firmware TinyUSB MSC state machine against a delayed worker.
Configure/build firmware first: its pinned patched driver is generated by CMake.
No attached USB device is accessed.
"""
import argparse
from pathlib import Path
import subprocess
import tempfile

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--sdk', type=Path, required=True)
parser.add_argument('--firmware-build', type=Path, required=True)
parser.add_argument('--sanitize', action='store_true')
args = parser.parse_args()
root = Path(__file__).resolve().parents[1]
driver = (args.firmware_build / 'msc_device_pipeline.c').resolve()
if not driver.is_file():
    parser.error('configure the firmware build first to generate the patched driver')
with tempfile.TemporaryDirectory(prefix='fv-msc-driver-') as tmp:
    for size in (4096, 16384, 32768):
        binary = Path(tmp) / f'msc-{size}'
        command = ['cc', '-std=c11', '-g', '-DCFG_TUSB_MCU=OPT_MCU_NRF5X',
                   '-DFV_USB_MSC=1', f'-DFV_USB_IO_BYTES={size}',
                   f'-DFV_MSC_DRIVER_FILE="{driver}"',
                   '-I' + str(root / 'firmware/security'),
                   '-I' + str(args.sdk.resolve() / 'lib/tinyusb/src'),
                   '-I' + str(root / 'src/storage/include'),
                   str(root / 'tests/usb_pipeline_driver_tests.c'),
                   str(root / 'firmware/security/usb_storage.c'), '-o', str(binary)]
        if args.sanitize:
            command += ['-fsanitize=address,undefined', '-fno-omit-frame-pointer', '-no-pie']
        subprocess.run(command, check=True)
        subprocess.run([str(binary)], check=True)
        print(f'PASS: {size}-byte buffers', flush=True)
