#ifndef FV_UI_SETTINGS_H
#define FV_UI_SETTINGS_H
typedef enum {
    UI_SETTING_POLICY,
    UI_SETTING_ERASE,
    UI_SETTING_METHOD,
    UI_SETTING_FIDO_INIT,
    UI_SETTING_FIDO_POLICY,
    UI_SETTING_PASSKEYS,
    UI_SETTING_COUNT
} ui_setting;
#endif
