#ifndef FUSE_VAULT_TUSB_CONFIG_H
#define FUSE_VAULT_TUSB_CONFIG_H

#ifndef CFG_TUSB_OS
#define CFG_TUSB_OS OPT_OS_NONE
#endif
#define CFG_TUD_ENABLED 1
#define CFG_TUSB_RHPORT0_MODE (OPT_MODE_DEVICE | OPT_MODE_FULL_SPEED)
#define CFG_TUD_ENDPOINT0_SIZE 64
#define CFG_TUD_CDC 0
#define CFG_TUD_MSC 1
#ifndef FUSE_VAULT_ENABLE_FIDO2
#define FUSE_VAULT_ENABLE_FIDO2 0
#endif
#define CFG_TUD_HID FUSE_VAULT_ENABLE_FIDO2
#define CFG_TUD_HID_EP_BUFSIZE 64
#define CFG_TUD_MIDI 0
#define CFG_TUD_VENDOR 0
#define CFG_TUD_MSC_EP_BUFSIZE 512
#ifndef CFG_TUSB_MEM_ALIGN
#define CFG_TUSB_MEM_ALIGN __attribute__((aligned(4)))
#endif

#endif
