#!/usr/bin/env python3
"""Bake the C splash renderer into flash frames; optionally write an animated preview."""
import argparse
from pathlib import Path
import re
import subprocess
import tempfile

root = Path(__file__).resolve().parents[3]
ui = root / 'src/shared/ui'
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--preview', type=Path)
args = parser.parse_args()
manifest = (ui / 'CMakeLists.txt').read_text().split('add_library(fv_ui STATIC', 1)[1].split(')', 1)[0]
sources = [str(ui / name) for name in re.findall(r'[\w/]+\.c', manifest)]
with tempfile.TemporaryDirectory() as temp:
    temp = Path(temp)
    source = temp / 'frames.c'
    source.write_text('''#include "drawing.h"
#include <stdio.h>
int main(void) {
    fv_ui u;
    for(unsigned f=0;f<10;f++) {
        ui_draw_splash(&u,f);
        if(fwrite(u.framebuffer,1,FV_SCREEN_BYTES,stdout)!=FV_SCREEN_BYTES)return 1;
    }
    return 0;
}
''')
    subprocess.run(['cc', '-std=c11', '-I', str(ui), str(source), *sources, '-o', str(temp/'frames')], check=True)
    data = subprocess.check_output([str(temp/'frames')])
assert len(data) == 128000
# Indexed palette halves flash use; no second RAM framebuffer is needed.
palette = sorted(set(data))
assert len(palette) <= 16
indices = {v:i for i,v in enumerate(palette)}
packed = bytes((indices[data[i]] << 4) | indices[data[i+1]] for i in range(0,len(data),2))
output = root / 'src/pico/platform/startup_frames.inc'
output.write_text('/* Generated by src/host/tools/generate_splash.py; do not edit. */\n'
    + 'static const uint8_t startup_palette[] = {' + ','.join(map(str,palette)) + '};\n'
    + 'static const uint8_t startup_frames[10][6400] = {\n'
    + ',\n'.join('{\n' + '\n'.join(','.join(map(str,packed[f*6400+i:f*6400+i+80]))+',' for i in range(0,6400,80)) + '\n}' for f in range(10)) + '\n};\n')
if args.preview:
    from PIL import Image
    from device_ui import rgb_bytes
    frames = [Image.frombytes('RGB',(160,80),rgb_bytes(data[f*12800:(f+1)*12800])).resize((640,320),Image.Resampling.NEAREST) for f in range(10)]
    args.preview.parent.mkdir(parents=True,exist_ok=True)
    frames[0].save(args.preview,save_all=True,append_images=frames[1:],duration=50,loop=0)
